name: AAssaly
favicon: null
layout_spectrum: 0.59965
typography_spectrum: 0.9820769319776446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c17d11'
    - '#000000'
    - '#edd400'
    - '#ffffff'
    - '#3465a4'
  brandStrength: 0.375
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
