name: AAssaly
favicon: null
layout_spectrum: 0.85347
typography_spectrum: 0.93478
title: AAssaly
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#170c14'
    - '#40fb88'
    - '#e6d256'
    - '#1f8b36'
    - '#a18340'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
